before_install:
    - sudo apt-get update -qq
    - sudo apt-get install maven
language: java
jdk:
    - openjdk7
    - oraclejdk7
    - oraclejdk8
script: ./testAPI/test.sh
notifications:
  email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
      - Noad.arad@kaltura.com
      - Elad.cohen@kaltura.com
      - Jonathan.Kanarek@kaltura.com
    on_success: change
    on_failure: always
